services:
  postgres:
    image: postgres
    container_name: travago-rating-postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
    ports:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: travago-rating-pgadmin
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '5050:80'  # Access pgAdmin at http://localhost:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=$EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$DB_PASSWORD
    depends_on:
      - postgres

volumes:
  db: