services:
  mongodb:
    image: mongo
    container_name: travago-hotel-mongo
    environment:
      - 'MONGO_INITDB_DATABASE=travago'
      - 'MONGO_INITDB_ROOT_PASSWORD=Pranav123'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'

  mongo-express:
    image: mongo-express
    container_name: travago-hotel-mongo-express
    ports:
      - '5051:8081'  # Access mongo-express at http://localhost:5051
    environment:
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=Pranav@123'