services:
  mongo_db:
    image: mongo
    container_name: travago-hotel-mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - '27017'
    volumes:
      - db:/data/db

  mongo-express:
    image: mongo-express
    container_name: travago-hotel-mongo-express
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '5051:8081'  # Access mongo-express at http://localhost:5051
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD

volumes:
  db: