spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  docker:
    compose:
      enabled: true
      lifecycle-management: START_AND_STOP
      profiles:
        active: dev
      file: rating-service/compose-dev.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

