services:
  mysql:
    image: mysql
    container_name: travago-rating-mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - '3306'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: